
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dshuais
    password: 1zALwIgcJqeAdOvv
    url: jdbc:mysql://mysql.sqlpub.com:3306/dshuaishomepage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false


server:
  port: 8899